### ISSUE TITLE
error when  ng serve /npm start

### ISSUE THREAD

**Issue by ChiakiYu** [aspnetboilerplate/abp-ng2-module#11]
I downloaded the latest template (asp.net core & angular)
And use vscode to open the angular folder,
Execute `npm install`, `serve serve` error:

![image](https://user-images.githubusercontent.com/9720473/30577309-f8afd796-9d3f-11e7-8721-7c53beafa119.png)

I use the package version：
```
F:\Download\ChiakiYu\3.0.0\angular>ng -v
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.4.2
node: 6.10.2
os: win32 x64
@angular/animations: 4.4.2
@angular/common: 4.4.2
@angular/compiler: 4.4.2
@angular/core: 4.4.2
@angular/forms: 4.4.2
@angular/http: 4.4.2
@angular/platform-browser: 4.4.2
@angular/platform-browser-dynamic: 4.4.2
@angular/router: 4.4.2
@angular/cli: 1.4.2
@angular/compiler-cli: 4.4.2
typescript: 2.5.2
```

**Comment by ChiakiYu** [comment]
By the way, yesterday, everything is good

**Comment by ismcagdas** [comment]
@ChiakiYu can you remove node_modules folder and install packages with yarn ?
Probably new version of angular is installed and it causes this problem. We haven't worked on updating to new version of angular.

**Comment by ChiakiYu** [comment]
I deleted the abp-related package code, and then add, everything is fine, really strange
