### ISSUE TITLE
Rewrite AbpHttp to HttpClient

### ISSUE THREAD

**Issue by reberinformatik** [aspnetboilerplate/abp-ng2-module#14]
In order to use Angular 5, `Http` was deprecated. We should rewrite `AbpHttp` to extend or intercept `HttpClient` (or both) (see https://angular.io/guide/http#intercepting-all-requests-or-responses).
~~I would suggest, that you extend `HttpClient` to catch exceptions as you did in `AbpHttp` (see https://stackoverflow.com/a/46019852/463890).~~
You could provide one or several **interceptors** to add **headers** (see https://angular.io/guide/http#setting-new-headers) and **exception** handling (see https://stackoverflow.com/a/46021824/463890).

Finally, nswag must be reconfigured to use `HttpClient` instead of `Http`.

https://github.com/aspnetboilerplate/abp-ng2-module/blob/1af4756008d3fefc1b98a885907efc360b38f861/src/abpHttp.ts#L210

**Comment by hikalkan** [comment]
We will work on that. Thanks.

**Comment by ismcagdas** [comment]
abpHttp is removed and abpHttpInterceptor is introduced. Usage of abpHttpInterceptor is added to readme file.
