### ISSUE TITLE
Issue after upgrading my application to angular 5

### ISSUE THREAD

**Issue by iyhammad** [aspnetboilerplate/abp-ng2-module#17]
Hi,

I got the below error after upgrading my application to angular 5
`
ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider
replacing the function or lambda with a reference to an exported function (position 194:31 in the original .ts file), resolving symbol NgModule in D:/Work/src/MySystem/src/Clients/lo/node_modules/abp-ng2-module/node_modules/@angular/core/core.d.ts, resolving symbol AbpModule in D:/Work/src/MySystem/src/Clients/lo/node_modules/abp-ng2-module/src/abp.module.ts, resolving symbol AbpModule in D:/Work/src/MySystem/src/Clients/lo/node_modules/abp-ng2-module/src/abp.module.ts
`
This is my dependencies 
`
{
   "dependencies":{
      "@agm/core":"1.0.0-beta.2",
      "@angular/animations":"5.0.3",
      "@angular/cdk":"5.0.0-rc.1",
      "@angular/common":"5.0.3",
      "@angular/compiler":"5.0.3",
      "@angular/core":"5.0.3",
      "@angular/flex-layout":"2.0.0-beta.10-4905443",
      "@angular/forms":"5.0.3",
      "@angular/http":"5.0.3",
      "@angular/material":"5.0.0-rc.1",
      "@angular/material-moment-adapter":"5.0.0-rc.1",
      "@angular/platform-browser":"5.0.3",
      "@angular/platform-browser-dynamic":"5.0.3",
      "@angular/router":"5.0.3",
      "@ngx-translate/core":"8.0.0",
      "@swimlane/ngx-charts":"7.0.1",
      "@swimlane/ngx-datatable":"11.1.4",
      "@types/jquery":"^2.0.41",
      "@types/moment-timezone":"^0.2.34",
      "@withinpixels/ngx-dnd":"3.1.0",
      "abp-ng2-module":"1.3.0",
      "abp-web-resources":"3.2.3",
      "angular-calendar":"0.22.1",
      "angular-in-memory-web-api":"0.5.1",
      "angular2-markdown":"1.6.0",
      "classlist.js":"1.1.20150312",
      "core-js":"2.5.1",
      "d3":"4.12.0",
      "hammerjs":"2.0.8",
      "highlight.js":"9.12.0",
      "intl":"1.2.5",
      "jquery":"^3.1.1",
      "js-cookie":"2.1.4",
      "moment":"2.19.2",
      "moment-timezone":"0.5.14",
      "ngx-color-picker":"5.0.4",
      "ngx-cookie-service":"1.0.9",
      "nswag":"11.12.10",
      "perfect-scrollbar":"1.2.0",
      "rxjs":"5.5.2",
      "web-animations-js":"2.3.1",
      "zone.js":"0.8.18"
   },
   "devDependencies":{
      "@angular/cli":"1.5.0",
      "@angular/compiler-cli":"5.0.3",
      "@angular/language-service":"5.0.3",
      "@angularclass/hmr":"2.1.3",
      "@types/jasmine":"2.5.54",
      "@types/jasminewd2":"2.0.3",
      "@types/node":"6.0.92",
      "codelyzer":"4.0.1",
      "jasmine-core":"2.6.4",
      "jasmine-spec-reporter":"4.1.1",
      "karma":"1.7.1",
      "karma-chrome-launcher":"2.1.1",
      "karma-cli":"1.0.1",
      "karma-coverage-istanbul-reporter":"1.3.0",
      "karma-jasmine":"1.1.0",
      "karma-jasmine-html-reporter":"0.2.2",
      "protractor":"5.1.2",
      "ts-node":"3.2.2",
      "tslint":"5.7.0",
      "typescript":"2.4.2"
   }
}
`
I'm using Yarn
Yarn Version:  1.3.2
npm Version: 5.5.1
I noticed that the abp-ng2-module folder has dist, src and node_modules folders in it. the node_modules  contains @angular core and http modules in it. Is it normal?
--node_modules
---- abp-ng2-module
-------dist
-------src
-------node_modules
----------@angular
--------------core
--------------http

**Comment by ismcagdas** [comment]
@iyhammad it's not normal. In the previous versions of abp-ng2-module, I had a similar problem but it was fixed with latest version 1.3.0.

Can you run the project when you delete the node_modules folder manually under abp-ng2-module folder ? If so, try to clean npm cache and make a clean install for npm packages using yarn. If it does not work, we will try to reproduce your problem.

**Comment by iyhammad** [comment]
@ismcagdas Thank you for your reply. 
Deleting the node_modules resolved the issue. However I did `npm cache clean --force` and then `yarn install` and the abp-ng2-module come again with node_modules and it breaks the build.

**Comment by ismcagdas** [comment]
@iyhammad are you trying this on aspnetzero or free angular2 template ?

**Comment by iyhammad** [comment]
@ismcagdas It's a free angular2 template

**Comment by ismcagdas** [comment]
@iyhammad updating npm dependencies solved this issue. See and https://github.com/aspnetboilerplate/module-zero-core-template/commit/a175882cd3270496148859dc29a3ae400331a206.

Please reopen if it will not work for you.

**Comment by iyhammad** [comment]
@ismcagdas I confirm it's resolved now. I had to change the angular and moment packages versions from something like this `5.0.3` to `^5.0.3` the fixed version didn't work.
