### ISSUE TITLE
HttpClientModule shouldn't be imported in the library

### ISSUE THREAD

**Issue by iyhammad** [aspnetboilerplate/abp-ng2-module#22]
As per this issue https://github.com/angular/angular/issues/20575 , HttpClientModule shouldn't be imported in any library and should be only imported in the root application module.
Doing so, will reset the interceptors registered in the root module.
I don't know if this issue happening only with me because I'm doing this temporary https://github.com/aspnetboilerplate/abp-ng2-module/issues/18#issuecomment-372330068 or not.

**Comment by ismcagdas** [comment]
@iyhammad I didn't know there was such a behaviour, thank you for sharing this.
But, what can we do about it in abp-ng2-module ? I tihnk users of abp-ng2-module must use it according to rules of angular properly.

**Comment by iyhammad** [comment]
abp-ng2-module is just needs to remove HttpClientModule import and it will just work. However, It needs some testing from people who don't have my current issue https://github.com/aspnetboilerplate/abp-ng2-module/issues/18#issuecomment-372330068 .
As per the angular issue, HttpClientModule doesn't have something for libraries like abp-ng2-module to import and shouldn't be imported in there.

**Comment by ismcagdas** [comment]
@iyhammad I will test it like that, thanks.
