### ISSUE TITLE
Compatibility with angular 4 

### ISSUE THREAD

**Issue by MoatazGitHub** [aspnetboilerplate/abp-ng2-module#24]
I'm using 
"name": "abp-zero-template",
  "version": "4.0.0",

but when try to type **npm start** I get this error
![image](https://user-images.githubusercontent.com/17373050/39081941-c10781a0-454a-11e8-94ce-d6fb31e31ca0.png)

Please help

**Comment by ismcagdas** [comment]
@MoatazGitHub what is your abp-ng2-module version ? Try to remove node_modules folder and install it again using yarn.

**Comment by MoatazGitHub** [comment]
"abp-ng2-module": "^1.2.0",
    "abp-web-resources": "^2.2.1",

I tried to remove node_modules but still fails

**Comment by ismcagdas** [comment]
@MoatazGitHub I couldn't figure out the problem. Are you using mode-zero-core-template or AspNet Zero template ?
