### ISSUE TITLE
ABP_HTTP_PROVIDER missing

### ISSUE THREAD

**Issue by armory09** [aspnetboilerplate/abp-ng2-module#25]
Hi,

I recently updated my abp-ng2-module from 1.2.0 to 2.1.0.
after the update i'm getting an error ABP_HTTP_PROVIDER is not found

`import { AbpModule , ABP_HTTP_PROVIDER } from '@abp/abp.module';`
`providers: [
        ABP_HTTP_PROVIDER,`

Please help.

Thanks.

**Comment by ismcagdas** [comment]
ABP_HTTP_PROVIDER is removed in this issue https://github.com/aspnetboilerplate/abp-ng2-module/issues/14. Now, Angular's Http Interceptor is used. Please check usage of AbpHttpInterceptor instead https://github.com/aspnetboilerplate/abp-ng2-module#abphttpinterceptor.

**Comment by JigneshPatel04** [comment]
Before I have used "import { AbpModule, ABP_HTTP_PROVIDER } from '@abp/abp.module';"

but ABP_HTTP_PROVIDER  is not found this module , 
so I have used 
import { AbpHttpInterceptor } from '@abp/abpHttpInterceptor';
import { HTTP_INTERCEPTORS } from '@angular/common/http';

**Comment by ismcagdas** [comment]
it should be;

```
import { AbpHttpInterceptor } from '@abp/abpHttpInterceptor';
import { HTTP_INTERCEPTORS } from '@angular/common/http';
```

please check the provided link.

**Comment by JigneshPatel04** [comment]
Yes I have used that type .

import { API_BASE_URL } from '@shared/service-proxies/service-proxies';

providers: [
    AbpHttpInterceptor,
    { provide: API_BASE_URL, useFactory: getRemoteServiceBaseUrl }
  ]
is this okay ?

**Comment by ismcagdas** [comment]
use it like this;

```ts
providers: [
    { provide: HTTP_INTERCEPTORS, useClass: AbpHttpInterceptor, multi: true },
	...
}
```

**Comment by JigneshPatel04** [comment]
Without update _body: object but now it comes to string. I don't know why it comes to string. Know?

![image](https://user-images.githubusercontent.com/7892462/41042290-e5790002-69be-11e8-94f5-de9a5d7b30b7.png)

**Comment by ismcagdas** [comment]
@JigneshPatel04 I don't know why this happens. Does this work for you ? If not, what is the error ?

**Comment by JigneshPatel04** [comment]
I have used "nswag": "11.12.10" or any lastest version with rxjs 6.

Can we upgrade nswag ?

**Comment by ismcagdas** [comment]
we are using 11.12.7 in https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/package.json#L87 without a problem.

**Comment by JigneshPatel04** [comment]
https://github.com/RSuter/NSwag/issues/1369 . I have added some more imformation there. If any idea ?
