### ISSUE TITLE
abp-user-configuration.service.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by armory09** [aspnetboilerplate/abp-ng2-module#27]
I'm getting this error during build
![image](https://user-images.githubusercontent.com/6113947/40408545-786bbb16-5e57-11e8-87c5-49c401be3e76.png)

This is my package
![image](https://user-images.githubusercontent.com/6113947/40408634-b82e44f8-5e57-11e8-8208-c47f6627c365.png)

tsconfig.json
![image](https://user-images.githubusercontent.com/6113947/40408676-e1105384-5e57-11e8-912e-5feeec87997d.png)

Please help thanks

**Comment by ismcagdas** [comment]
@armory09 could you change "@abp/*" like below;

`"@abp/*": [ "../node_modules/abp-ng2-module/dist/src/*" ]`

**Comment by armory09** [comment]
@ismcagdas thanks for the response. im getting a different error
![image](https://user-images.githubusercontent.com/6113947/40409275-d308f9ba-5e59-11e8-9c13-e3dd12470f48.png)

**Comment by ismcagdas** [comment]
@armory09 could you remove node_modules folder and install it again ?

**Comment by armory09** [comment]
@ismcagdas after trying your suggestion, removing the node_modules folder then install it again. im still facing the same error in the second screen shots.

![image](https://user-images.githubusercontent.com/6113947/40410751-0940c84c-5e5e-11e8-8e06-66a3e0915d4a.png)

**Comment by ismcagdas** [comment]
@armory09 are you using ABP's ASP.NET Core & angular template ?

**Comment by armory09** [comment]
@ismcagdas yes im using that template.

**Comment by ismcagdas** [comment]
@armory09 I will try to upgrade our template to Angular 6.0.2 today. So you can compare it with your version. Could that work for you ?

**Comment by armory09** [comment]
yes please, thanks @ismcagdas

**Comment by ismcagdas** [comment]
@armory09 done in https://github.com/aspnetboilerplate/module-zero-core-template/issues/232.

**Comment by ezra2310** [comment]
**Im upgraded to 6 then getting the below, anybody have solution to fix the error ?**



> ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
> Module build failed: Error: F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
>     at AngularCompilerPlugin.getCompiledFile (F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
>     at plugin.done.then (F:\Project\SourceCode\AlphaPhe\3\aspnet-core\src\AnkaaConsulting.APhe.Web.Host\node_modules\@ngtools\webpack\src\loader.js:41:31)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by ismcagdas** [comment]
@ezra2310 do you have the below line in your tsconfig.json ?

`"@abp/*": [ "../node_modules/abp-ng2-module/dist/src/*" ]`

**Comment by pantonis** [comment]
@ismcagdas Yes I have it and still getting this error.

**Comment by armory09** [comment]
@ezra2310  and @pantonis 
have you tried to include abp-ng2-module in your tsconfig?
something like this:
![image](https://user-images.githubusercontent.com/6113947/42311515-8f3da85c-802d-11e8-9334-f302e7303db2.png)

**Comment by pantonis** [comment]
@armory09 which tsconfig? can you post the path to it and if possible the whole tsconfig.json file?

Thanks

**Comment by armory09** [comment]
@pantonis  your main tsconfig if you have multiple

**Comment by pantonis** [comment]
@armory09 it worked man. You are a lifesaver. Thanks

**Comment by ezra2310** [comment]
@armory09 : Thanks compiled and build successfully. Thanks a lot.
But could not able to login, the below error,

**WARN: 
abp.js:350 Unexpected authenticateResult!**

Can you pls help me once again ;-)

**Comment by armory09** [comment]
@ezra2310 
I'm believe i already face this issue before, but i can't remember what i did, have you tried to rebuild your `service-proxies.ts`?
run nswag cli

**Comment by ezra2310** [comment]
@ezra2310 : I tried but still not login same warning coming

**Comment by ezra2310** [comment]
@ismcagdas: Thank you sooo much. After make changes in proxies module could able to login and application working well. Thanks a lot @ismcagdas

**Comment by ismcagdas** [comment]
@brunobertechini I'm not sure if this is related to abp-ng2-module or angular-cli itself. If you have a suggestion to the problem, we can try it.

**Comment by zhipengyue** [comment]
hey! I had the same error in angular5,and finally i solved it.  But it not something wrong in tsconfg.json. 
My be you import somthing ts files in your project, but some character capitalized, and the editor don't displayed error. like this ...
import { FormItemBase } from '../form-item-Base';
but when you package your project , the error appeared.

**Comment by ismcagdas** [comment]
@zhipengyue thanks, we can check if the imports and file names are the same or not.

**Comment by adhivenkatesh** [comment]
Hi i have changed difference directory and deleted ng_moduules directory , i spent 2 days did not get solution for the below error , please help get out from this error , thanks in advance :

----------------------------------
ERROR in ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\AngularProjects\AngularRouting\Routing\src\main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\AngularProjects\AngularRouting\Routing\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (D:\AngularProjects\AngularRouting\Routing\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: D:\AngularProjects\AngularRouting\Routing\src\polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (D:\AngularProjects\AngularRouting\Routing\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (D:\AngularProjects\AngularRouting\Routing\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
-------------------------------------------------------------

**Comment by ismcagdas** [comment]
@adhivenkatesh I don't see anything related to abp-ng2-module in the error message you shared.

**Comment by adhivenkatesh** [comment]
Hi Thanks for your response, I am using Angular  7 version 

I dont know about  "abp-ng2-module "

**Comment by ismcagdas** [comment]
So why did you create the issue here ? Because this is the repository for **abp-ng2-module**

**Comment by adhivenkatesh** [comment]
Hi ismcagdas,  thanks for your response i dont know about "repository for abp-ng2-module"

Can you help for the below error :
--------------------------------------

ERROR in node_modules/rxjs/src/internal/scheduled/scheduled.ts(25,40): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of
type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?:
T) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerAction<T>' is
not assignable to type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerAction<T>'.
            Types of property 'schedule' are incompatible.
              Type '(state?: T, delay?: number) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type '(state?: T, delay?: number) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription'.
                Type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription' is not assignable to type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription'.
                  Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(27,37): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(29,35): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/scheduled/scheduled.ts(31,38): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike'.
node_modules/rxjs/src/internal/observable/from.ts(116,29): error TS2345: Argument of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerLike' is not assignable to parameter of type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerLike'.
  Types of property 'schedule' are incompatible.
    Type '<T>(work: (this: import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type '<T>(work: (this: import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerAction<T>, state?: T) => void, delay?: number, state?: T) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription'.
      Types of parameters 'work' and 'work' are incompatible.
        The 'this' types of each signature are incompatible.
          Type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/types").SchedulerAction<T>' is not assignable to type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/types").SchedulerAction<T>'.
            Types of property 'schedule' are incompatible.
              Type '(state?: T, delay?: number) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type '(state?: T, delay?: number) => import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription'.
                Type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/src/internal/Subscription").Subscription' is not assignable to type 'import("D:/AngularProjects/BestRouting/node_modules/rxjs/internal/Subscription").Subscription'.
                  Property '_parentOrParents' is protected but type 'Subscription' is not a class derived from 'Subscription'.
=====================================

**Comment by acjh** [comment]
@adhivenkatesh This is **not** a help site for other projects.

**Comment by adhivenkatesh** [comment]
Thanks acjh for ur response , then how to come out of this error ?

**Comment by acjh** [comment]
Find the repository for that project and then ask there.

**Comment by adhivenkatesh** [comment]
How to find repository for this project ?

**Comment by acjh** [comment]
Google it.

**Comment by adhivenkatesh** [comment]
ohh.. ok ok understood , , Thanks .
