### ISSUE TITLE
Module build failed

### ISSUE THREAD

**Issue by JigneshPatel04** [aspnetboilerplate/abp-ng2-module#28]
Hello,
I have upgrade angular 6 + abp and I am running ng server then I got below errors.
I have used  
"abp-ng2-module": "^1.3.0",
 "abp-web-resources": "^3.2.3", in package.json file. 
anything change on my project. ?

tsconfig.json 

 "paths": {
      "@abp/*": [ "../node_modules/abp-ng2-module/src/*" ],
      "@app/*": [ "./app/*" ],
      "@shared/*": [ "./shared/*" ],
      "@node_modules/*": [ "../node_modules/*" ]
    }

![modul_load_fail](https://user-images.githubusercontent.com/7892462/40911812-723e113e-680d-11e8-9372-2e16cc23e8ea.PNG)

**Comment by ismcagdas** [comment]
@JigneshPatel04 you must use abp-ng2-module's v3.0.

`"abp-ng2-module": "^3.0.0"`

**Comment by JigneshPatel04** [comment]
I have updated "abp-ng2-module": "^3.0.0" and npm install then show many errors occured.
errors : 
Property 'of' does not exist on type 'typeof Observable'.
Property 'flatMap' does not exist on type 'Observable<Response>
Property 'map' does not exist on type 'Observable<Response>'.
error TS2339: Property 'finally' does not exist on type 'Observable<void>'.

**Comment by ismcagdas** [comment]
@JigneshPatel04 you also need to upgrade RxJs to 6.x. Please follow their guide https://github.com/ReactiveX/rxjs/blob/master/docs_app/content/guide/v6/migration.md. If you have some packages which requires RxJs 5.x, you can use rxjs-compat.

**Comment by JigneshPatel04** [comment]
I have followed and resolved errors .
Now I got below error ; I didn't know.

ERROR in Source file not found: '/d/Project/YourItStaffResume/SSP_ERP/aspnet-core/src/YITS.SSP_ERP.Web.Host/src/app/shared/index.ts'.
error TS2307: Cannot find module '@abp/abpHttp'.

**Comment by ismcagdas** [comment]
@JigneshPatel04 I think this is not related to abp-ng2-module. Please search it on angular or angular-cli github repositories.

**Comment by JigneshPatel04** [comment]
Ok thanks ,

ERROR in ./node_modules/abp-ng2-module/src/abp-user-configuration.service.ts
Module build failed: Error: d:\Jignesh\Project\YourItStaffResume\SSP_ERP\aspnet-core\src\YITS.SSP_ERP.Web.Host\node_modules\abp-ng2-module\src\abp-user-configuration.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (d:\Jignesh\Project\YourItStaffResume\SSP_ERP\aspnet-core\src\YITS.SSP_ERP.Web.Host\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (d:\Jignesh\Project\YourItStaffResume\SSP_ERP\aspnet-core\src\YITS.SSP_ERP.Web.Host\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

I have got this error

**Comment by ismcagdas** [comment]
could you check the value of "@abp/*" in your tsconfig.json ? It must be like;

`"@abp/*": [ "../node_modules/abp-ng2-module/dist/src/*" ]`

**Comment by JigneshPatel04** [comment]
Yes I have used "@abp/*": [ "../node_modules/abp-ng2-module/src/*" ].  So error occured. but now i used "/dist/src/*"
thanks for reply and helping.

**Comment by JigneshPatel04** [comment]
Just only said .. I know this is package issues or other.

I have used angular 5 + abp in my project. then I have logged in my project. now I have updated angular 6 then I have not logged in it. Unexpected authenticateResult!. error.

I have entered true username and pwd but I don't know why login fail.
Now '_body' comes as a string but ago without the update, it came as an object. 
do you know?

**Comment by ismcagdas** [comment]
are you using AbpHttpInterceptor in your project https://github.com/aspnetboilerplate/abp-ng2-module#abphttpinterceptor ?

**Comment by wombelite** [comment]
> could you check the value of "@abp/*" in your tsconfig.json ? It must be like;
> 
> `"@abp/*": [ "../node_modules/abp-ng2-module/dist/src/*" ]`

Thanks @ismcagdas I was looking at this for ages not realising I had **missed** the `dist` before the `src`
