### ISSUE TITLE
Errors in service-proxies.ts because upgrade angular 6 

### ISSUE THREAD

**Issue by JigneshPatel04** [aspnetboilerplate/abp-ng2-module#29]
Hello,
I have upgrade other projects with "https://update.angular.io/". 
I have got errors :
-- ERROR in src/shared/service-proxies/service-proxies.ts(17,10): error TS2305: Module '"d:/Project/BackUp/SSP_ERP/aspnet-core/src/YITS.SSP_ERP.Web.Host/node_modules/rxjs/Observable"' has no exported member 'Observable'.
--src/shared/service-proxies/service-proxies.ts(55,50): error TS2339: Property 'flatMap' does not exist on type 'Observable<Response>'.

I don't know how to upgrade in the service-proxies.ts file because I have used nswag.

**Comment by ismcagdas** [comment]
@JigneshPatel04 upgrade to latest NSWAG and `"rxJsVersion": 6.0` to your 'angular/nswag/service.config.nswag' file and regenerate your service proxy files.

This is not related to abp-ng2-module.

**Comment by JigneshPatel04** [comment]
I referred https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/nswag/service.config.nswag link but you didn't use "rxJsVersion": 6.0 .
My service.config.nswag file .

{
  "swaggerGenerator": {
    "fromSwagger": {
      "url": "http://localhost:22742/swagger/v1/swagger.json",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}ServiceProxy",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 1.8,
      "template": "Angular",
      "promiseType": "Promise",
      "dateTimeType": "MomentJS",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "wrapDtoExceptions": false,
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromPathSegments",
      "markOptionalProperties": false,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "extensionCode": "service.extensions.ts",
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "importRequiredTypes": true,
      "baseUrlTokenName": "API_BASE_URL",
      "injectionTokenType": "InjectionToken",
      "output": "../src/shared/service-proxies/service-proxies.ts"
    },
    "swaggerToCSharpClient": {
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateDtoTypes": true,
      "injectHttpClient": false,
      "disposeHttpClient": true,
      "generateExceptionClasses": true,
      "exceptionClass": "SwaggerException",
      "wrapDtoExceptions": true,
      "useHttpClientCreationMethod": false,
      "httpClientType": "System.Net.Http.HttpClient",
      "useHttpRequestMessageCreationMethod": false,
      "useBaseUrl": true,
      "generateSyncMethods": false,
      "clientClassAccessModifier": "public",
      "generateContractsOutput": false,
      "className": "{controller}Client",
      "namespace": "MyNamespace",
      "generateOptionalParameters": false,
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTime",
      "dateTimeType": "System.DateTime",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.ObjectModel.ObservableCollection",
      "dictionaryType": "System.Collections.Generic.Dictionary",
      "classStyle": "Inpc",
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [],
      "wrapResponses": false,
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "output": null
    },
    "swaggerToCSharpController": {
      "className": "{controller}",
      "namespace": "MyNamespace",
      "additionalNamespaceUsages": [
        "System.Web.Http"
      ],
      "generateOptionalParameters": false,
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTime",
      "dateTimeType": "System.DateTime",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.Generic.IEnumerable",
      "dictionaryType": "System.Collections.Generic.Dictionary",
      "classStyle": "Inpc",
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [],
      "wrapResponses": false,
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "output": null
    }
  }
}

**Comment by ismcagdas** [comment]
@JigneshPatel04 yes we haven't upgraded to RxJs 6 yet for module-zero-core-template, see https://github.com/aspnetboilerplate/module-zero-core-template/issues/247.

**Comment by ismcagdas** [comment]
![resim](https://user-images.githubusercontent.com/4133525/41102545-d5800c16-6a6f-11e8-814b-c7b7c06bffaf.png)

**Comment by JigneshPatel04** [comment]
can we change "typeScriptVersion": 1.8, ??

**Comment by ismcagdas** [comment]
yes, you can change it to a higher version.

**Comment by JigneshPatel04** [comment]
I have updated 
      "typeScriptVersion": 2.7.2,
      "rxJsVersion": 6.0,
      "template": "Angular",
      "promiseType": "Promise",
...

I run refresh.bat command then below errors occurred.

![image](https://user-images.githubusercontent.com/7892462/41105112-8d638a3c-6a8a-11e8-89d6-0f4ca88a03af.png)

**Comment by JigneshPatel04** [comment]
I have updated service.config.nswag file 
 "typeScriptVersion": 2.7,
 "rxJsVersion": 6.0
_____________________
I have run command refresh.bat.
I have run npm start command then didn't resolve flatMap errors.
________________
- Module '"d://Project/BackUp/SSP_ERP/aspnet-core/src/YITS.SSP_ERP.Web.Host/node_modules/rxjs/Observable"' has no exported member 'Observable'.
- src/shared/service-proxies/service-proxies.ts(55,50): error TS2339: Property 'flatMap' does not exist on type 'Observable<Response>'.

I think nswag file didn't update yet.

**Comment by ismcagdas** [comment]
@JigneshPatel04 I suggest you to wait for https://github.com/aspnetboilerplate/module-zero-core-template/issues/247. When we finish it, you can apply same changes to your project.
