### ISSUE TITLE
Intercept Exception-Handling - Allow disabling of default exception message per request

### ISSUE THREAD

**Issue by reberinformatik** [aspnetboilerplate/abp-ng2-module#3]
We would like to have a way to catch the exception in the component and disable the default fallback (=sweet-alert popup) only for the current service-call.

I.e. something like this:
```
this.myService.myMethod(x, y).subscribe(
  data => console.log(data),
  err => {console.log(err); err.handled = true;}
);
```
Excepted behaviour:
Allow disabling of the default (sweet-) alert when a exception occurs per service-call.

Like in .NET I would like to have a mechanism to catch the exception so that it doesn't bubble up to the default handler.

It would be nice if you could implement such a feature 🥇

**Comment by hikalkan** [comment]
Thank you for creating the issue.

**Comment by g-guth** [comment]
Any news on this?

**Comment by hikalkan** [comment]
Haven't worked on that yet.

**Comment by hikalkan** [comment]
As I know, there is no way of knowing if error callback is provided inside AbpHttp. So, how can we pass a flag to let it know to not handle the error itself?

**Comment by vdurante** [comment]
I am not an expert in angular compared to you guys, but I just found a workaround if anyone is really desperate looking for a solution.

1. I downloaded the respository and added it to the `angular` folder of my project, naming it `abp-ng2-module-custom`
2. Deleted the npm package from node_modules and changed package.json from my project to `"abp-ng2-module": "file:abp-ng2-module-custom",`
3. In the src folder I added `AbpHttpSettings.ts`

```ts
export namespace AbpHttpSettings {
    export var ignoreErrors: boolean = false;
}
```

4. Added `export { AbpHttpSettings } from './AbpHttpSettings'` to `index.ts` of `src` folder in my custom module
5. Go to file `abpHttp.ts` and `import { AbpHttpSettings } from './AbpHttpSettings';`
6. In this file, now you need to change what you expect to be ignored. I decided to only modify the error handing function

```ts
handleError(error: Response): Observable<any> {
    var ajaxResponse = this.getAbpAjaxResponseOrNull(error);
    if (ajaxResponse != null) {
        if(!AbpHttpSettings.ignoreErrors){
            this.handleAbpResponse(error, ajaxResponse);
        }
        return Observable.throw(ajaxResponse.error);
    } else {
        if(!AbpHttpSettings.ignoreErrors){
            this.handleNonAbpErrorResponse(error);
        }
        return Observable.throw('HTTP error: ' + error.status + ', ' + error.statusText);
    }
}
```
7. I went to my `Component` where I really wanted to disable errors and added the following import `import { AbpHttpSettings } from 'abp-ng2-module';`

```ts
ngOnInit() {
    AbpHttpSettings.ignoreErrors = true;
}

ngOnDestroy() {
    AbpHttpSettings.ignoreErrors = false;
}
```
Not the best solution, as it needs to be reset to false when I leave the `Component`. But it works for now.

**Comment by ismcagdas** [comment]
Moved to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4574
