### ISSUE TITLE
I'm unable to add abp-ng2-module in an asp.net project using systemjs.config with angular 2 

### ISSUE THREAD

**Issue by Garybhardwaj** [aspnetboilerplate/abp-ng2-module#4]

**Comment by hikalkan** [comment]
Hi,

This is for Angular 4+. We use webpack (actually angular-cli) but since this is a standard ng4 module, it should work with systemjs approach too. Have you added module to your module imports?

**Comment by Garybhardwaj** [comment]
Hi,
Thanks for your quick response actaully i'm new to Angular i installed abp-ng2-module in my project using npm then i m trying to access abpmodule,Abphttp_provider in my component but its unable to find abp-module on runtime and i have mentioned it in package.json as well
this is my systemjs.config
`/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': '/node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      'app': 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
      'abpmodule': 'npm:abp-ng2-module/dist/bundles/abp-ng2-module.umd.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        defaultExtension: 'js',
        meta: {
          './*.js': {
            loader: 'systemjs-angular-loader.js'
          }
        }
      },
      rxjs: {
        defaultExtension: 'js'
      },
        abpmodule:{
            defaultExtension:'js'
        }
    }
  });
})(this);
`
this is my app.module.ts where i m importing it

import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AbpModule, ABP_HTTP_PROVIDER } from 'abpmodule/'

@NgModule({
    imports: [BrowserModule, AbpModule],
    declarations: [AppComponent],
    providers: [ABP_HTTP_PROVIDER],
    bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by hikalkan** [comment]
This project (https://github.com/aspnetboilerplate/module-zero-core-template/tree/master/angular) uses abp-ng2-module but it uses angular-cli approach (with webpack).

It seems you do it right, but as I said, never tested with system.js. If you write to stackoverflow, other people can help you: https://stackoverflow.com/questions/tagged/aspnetboilerplate

**Comment by Garybhardwaj** [comment]
hi,
I resolved this issue by correcting  keyword 'abpmodule' with 'abp-ng2-module' then it started working One more thing I would like to know whether  this Abp_http_provider works with Service Proxies as Abp with Angular js works ,any sample would be much helpful
