### ISSUE TITLE
abpHttpInterceptor converts "null" to {}

### ISSUE THREAD

**Issue by adorep** [aspnetboilerplate/abp-ng2-module#40]
On line 315 an empty response is converted to an empty object.

I think null or undefined (empty response) should not be changed to an empty object (not empty response).

**Comment by hikalkan** [comment]
Thanks for reporting. We will check why it's done like that.

**Comment by adorep** [comment]
I did some more investigation and maybe this is working as intended and the problem is on our side.
The service where this is a problem does not return a specific ResultDto but directly a string.

If returning a Dto is mandatory i'd say that this conversion is ok. The client would check a non-existent property and it would be null as expected.
If instead returning a ordinary string is not a problem than the client should receive null in case the server returns null.

**Comment by ismcagdas** [comment]
@adorep I'm not sure for now 😄 , let me check this.

**Comment by adorep** [comment]
@ismcagdas Did you already check if this behavior is intended?

**Comment by ismcagdas** [comment]
Moved to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4573
