### ISSUE TITLE
StaticInjectionError: InjectionToken HTTP_INTERCEPTORS -> AbpHttpConfiguration

### ISSUE THREAD

**Issue by Alucardz** [aspnetboilerplate/abp-ng2-module#47]
I can't seem to get this module to work with a minimal reproduction (versions and details are in the below repo):

The proxy-classes you see in there were generated using NSwag toolchain v11.17.14.0.

https://stackblitz.com/edit/angular-abp-interceptor-error

I tried with angular 5, 6 and 7, same problem.

I keep getting this:
```
StaticInjectorError(AppModule)[InjectionToken HTTP_INTERCEPTORS -> AbpHttpConfiguration]: 
  StaticInjectorError(Platform: core)[InjectionToken HTTP_INTERCEPTORS -> AbpHttpConfiguration]: 
    NullInjectorError: No provider for AbpHttpConfiguration!
    at NullInjector.get (injector.ts:39)
    at resolveToken (injector.ts:334)
    at tryResolveToken (injector.ts:276)
    at StaticInjector.get (injector.ts:156)
    at resolveToken (injector.ts:334)
    at tryResolveToken (injector.ts:276)
    at StaticInjector.get (injector.ts:156)
    at resolveNgModuleDep (ng_module.ts:124)
    at _callFactory (ng_module.ts:200)
    at _createProviderInstance (ng_module.ts:146)
```

**Comment by ismcagdas** [comment]
@Alucardz we are using a tsconfig file https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/tsconfig.json, maybe that is why you are getting this error.

**Comment by Alucardz** [comment]
> @Alucardz we are using a tsconfig file https://github.com/aspnetboilerplate/module-zero-core-template/blob/master/angular/src/tsconfig.json, maybe that is why you are getting this error because your version doesn't contain such a file.
> 
> Could you add a similar file and then inject AbpHttpInterceptor like below;
> 
> `import { AbpHttpInterceptor } from '@abp/abpHttpInterceptor';`

I had already tried that previously before posting this issue, same problem. 

Here's the same project with tsconfig.json set up just as you described:

[angular-abp-interceptor-error.zip](https://github.com/aspnetboilerplate/abp-ng2-module/files/2844250/angular-abp-interceptor-error.zip)

**Comment by Alucardz** [comment]
The only way I got it to work was to add:
```
      AbpHttpConfiguration,
      MessageService,
      LogService,
```
To the list of providers. but SURELY this doesn't make sense, I shouldn't have to mention all dependent providers when referencing an external module, right?

**Comment by Alucardz** [comment]
The problem is that `AbpModule` needs to be imported somewhere in the module hierarchy (e.g. in `services-proxy-module.ts`), because that's the module that exposes the missing providers. 

Perhaps modify the README.md to mention that?

**Comment by ismcagdas** [comment]
@Alucardz you are right, we will add it to Readme file, thanks.
