### ISSUE TITLE
Export services in the index.ts

### ISSUE THREAD

**Issue by matheo** [aspnetboilerplate/abp-ng2-module#53]
Why the Services are not exported in the entry-point?
this forces to import them individually from a subfolder of the package,
with no real need to overcomplicate this.
Thanks

**Comment by ismcagdas** [comment]
@matheo thanks, we will try that.

**Comment by ismcagdas** [comment]
Moved to https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4571
