### ISSUE TITLE
cant find name abp

### ISSUE THREAD

**Issue by laosandegudai** [aspnetboilerplate/abp-ng2-module#9]
I try use it in a new project of angular-cli,but i find this question.beacuse i try use abp to create a other ui.

**Comment by hikalkan** [comment]
Can you share more details (like a stack trace or exception message or a Visual Studio screenshot...)

**Comment by laosandegudai** [comment]
@hikalkan  Thank you very much,When i user 'cnpm' met this problem,Now I user 'npm' its ok.

**Comment by ismcagdas** [comment]
thanks for the feedback @laosandegudai.
